-- Tablas principales
create table if not exists branches ( id text primary key, name text not null, location text, is_active boolean default true );
create table if not exists categories ( id text primary key, name text not null, description text );
create table if not exists products ( id text primary key, category_id text references categories(id), name text not null, description text, price numeric not null, cost numeric not null, sku text, barcode text, stock integer not null, min_stock integer not null, has_variants boolean default false, variants jsonb, tax_rate numeric, status text not null );
create table if not exists inventory_levels ( id text primary key, product_id text references products(id) on delete cascade, branch_id text references branches(id) on delete cascade, quantity integer not null, variants jsonb );
create table if not exists customers ( id text primary key, name text not null, email text, phone text, address text, tax_id text, loyalty_points integer default 0 );
create table if not exists users ( id text primary key, name text not null, email text, role text not null, branch_id text references branches(id), supervisor_id text references users(id), base_salary numeric, commission_rate numeric, status text not null );
create table if not exists transactions ( id text primary key, branch_id text references branches(id), user_id text references users(id), customer_id text references customers(id), date timestamp with time zone not null, subtotal numeric not null, tax numeric not null, total numeric not null, status text not null, ncf text, ncf_type text, change_given numeric );
create table if not exists transaction_payments ( id text primary key, transaction_id text references transactions(id) on delete cascade, amount numeric not null, method text not null, currency_code text not null, exchange_rate numeric, bank_card_id text );
create table if not exists transaction_items ( id text primary key, transaction_id text references transactions(id) on delete cascade, product_id text references products(id), quantity integer not null, price numeric not null, cost numeric not null, tax numeric not null, variant_label text );
create table if not exists returns ( id text primary key, transaction_id text references transactions(id), product_id text references products(id), quantity integer not null, reason text not null, date timestamp with time zone not null, status text not null, type text not null, notes text );
create table if not exists warranties ( id text primary key, product_id text references products(id), product_name text not null, transaction_id text references transactions(id), customer_id text references customers(id), customer_name text, purchase_date timestamp with time zone not null, expiry_date timestamp with time zone not null, serial_number text, status text not null );
create table if not exists cash_sessions ( id text primary key, branch_id text references branches(id), opened_at timestamp with time zone not null, closed_at timestamp with time zone, opening_balance numeric not null, expected_balance numeric, status text not null, user_id text references users(id) );
create table if not exists cash_movements ( id text primary key, session_id text references cash_sessions(id) on delete cascade, type text not null, amount numeric not null, currency_code text not null, description text not null, date timestamp with time zone not null );
create table if not exists inventory_transfers ( id text primary key, product_id text references products(id), product_name text not null, from_branch_id text references branches(id), from_branch_name text, to_branch_id text references branches(id), to_branch_name text, variant_label text, quantity integer not null, variants jsonb, date timestamp with time zone not null, user_id text references users(id), status text not null );
create table if not exists suppliers ( id text primary key, name text not null, rnc text, email text, phone text, address text, type_of_merchandise text, rating integer );
create table if not exists supplier_orders ( id text primary key, supplier_id text references suppliers(id), date timestamp with time zone not null, expected_delivery_date timestamp with time zone, total numeric not null, status text not null, branch_id text references branches(id), transport_details text, transport_cost numeric );
create table if not exists supplier_order_items ( id text primary key, order_id text references supplier_orders(id) on delete cascade, product_id text references products(id), product_name text not null, variant_label text, quantity integer not null, cost numeric not null );
create table if not exists bank_cards ( id text primary key, name text not null, bank text not null, last_four text, balance numeric not null, currency text not null, is_active boolean default true );
create table if not exists bank_transactions ( id text primary key, card_id text references bank_cards(id), type text not null, amount numeric not null, date timestamp with time zone not null, reference text, description text not null, original_transaction_id uuid );
create table if not exists inventory_audits ( id text primary key, date timestamp with time zone not null, branch_id text references branches(id), user_id text references users(id), status text not null, notes text );
create table if not exists inventory_audit_items ( id text primary key, audit_id text references inventory_audits(id) on delete cascade, product_id text references products(id), product_name text not null, variant_label text, expected integer not null, actual integer not null, difference integer not null );
create table if not exists salary_settlements ( id text primary key, user_id text references users(id), user_name text not null, session_id text references cash_sessions(id), base_salary numeric not null, commissions numeric not null, total numeric not null, date timestamp with time zone not null, status text not null );
create table if not exists quotes ( id text primary key, branch_id text references branches(id), user_id text references users(id), customer_id text references customers(id), date timestamp with time zone not null, subtotal numeric not null, tax numeric not null, total numeric not null, status text not null, notes text );
create table if not exists quote_items ( id text primary key, quote_id text references quotes(id) on delete cascade, product_id text references products(id), product_name text not null, quantity integer not null, price numeric not null, tax numeric not null, variant_label text );
create table if not exists time_shifts ( id text primary key, user_id text references users(id), clock_in timestamp with time zone not null, clock_out timestamp with time zone, notes text );

-- Nota: Todas las tablas tienen "created_at timestamp with time zone default timezone('utc'::text, now()) not null"
-- Nota: Todas las tablas tienen "alter table <nombre> enable row level security;" y policies "Allow all for <nombre>"
